---
title: "New SEIR model (+QHD)"
author: "Linh Tang & Britney He"
date: "2/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The below code chunk is assuming 100% population is Non-Vulnerable

```{r}
N = 1000
p.vulnerable = 0
N.nv = N * (1 - p.vulnerable)

# Parameters Declaration for NV sub-population

### Mutable Parameters (Testing effectiveness, quarantine days)
p.test.sym.nv = 0 #percentage of testing for symptomatic group
p.test.asym.nv = 0 #percentage of testing for asymptomatic group
p.test.all.nv = p.test.asym.nv/2 #percentage of testing for all NV sub-population
p.fp.all.nv = .01 #false positive percentage of testing for all NV sub-population
p.tp.sym.nv = .98 #true positive percentage for symptomatic group
p.tp.asym.nv = .95 #true positive percentage for asymptomatic group
day.q = 14 #quarantine period (days)

### Immutatble Parameters (disease's rates)
p.ns.nv = .25 #percentage of initial non-susceptible
p.sym.nv = .5 #percentage of infected being symptomatic
day.i = 10 #incubation period (days)
E.rate = 1 / day.i #exposure rate

I.rate.sym.nv = 1 #infection rate for symptomatic group
I.rate.asym.nv = 1 #infection rate for asymptomatic group

H.rate.nv = .1 #hospitalization rate

R.rate.sym.nv = .09 #recovery rate for symptomatic group
R.rate.asym.nv = .1 #recovery rate for asymptomatic group
R.rate.h.nv = .05333 #recovery rate for hospitalized group

D.rate.sym.nv = .01 #death rate for symptomatic group
D.rate.asym.nv = .05 #death rate for asymptomatic group
D.rate.h.nv = 0.01333 #death rate for hospitalized group

df.nv = data.frame(Day = numeric(),
                Pop.nv = numeric(),
                S.nv = numeric(),
                FQ.nv = numeric (),
                E.nv = numeric(),
                Isym.nv = numeric(),
                Iasym.nv = numeric(),
                Qsym.nv = numeric(),
                Qasym.nv = numeric(),
                H.nv = numeric(),
                R.nv = numeric(),
                D.nv = numeric()
                # for debugging only
                # new.exposed.nv = numeric(),
                # quarantine.released.today.nv = numeric(),
                # new.quarantined.nv = numeric(),
                # new.infected.all.nv = numeric(),
                # new.infected.sym.nv = numeric(),
                # confirmed.sym.nv = numeric(),
                # nonconfirmed.sym.nv = numeric(),
                # new.infected.asym.nv = numeric(),
                # confirmed.asym.nv = numeric(),
                # nonconfirmed.asym.nv = numeric(),
                # nonconfirmed.sym.to.H.nv = numeric(),
                # nonconfirmed.sym.to.R.nv = numeric(),
                # nonconfirmed.sym.to.D.nv = numeric(),
                # nonconfirmed.asym.to.R.nv = numeric(),
                # Qsym.to.H.nv = numeric(),
                # Qsym.to.R.nv = numeric(),
                # Qsym.to.D.nv = numeric(),
                # Qasym.to.R.nv = numeric(),
                # H.to.R.nv = numeric(),
                # H.to.D.nv = numeric()
                )
for (i in 0:100) {
  
  if(i == 0){
    ### Initial setting (day 0)
    Isym.nv = 5 #initial infected symptomatic
    Iasym.nv = 0 #initial infected asymptomatic
    R.nv = N.nv * p.ns.nv #initial "recovered" i.e non-susceptible
    S.nv = N.nv - Isym.nv - Iasym.nv - R.nv
    FQ.nv = 0
    E.nv = 0
    D.nv = 0
    H.nv = 0
    Qsym.nv = 0
    Qasym.nv = 0
  } else {
    ### Current day calculations
    S.nv = S.nv + dS.nv
    FQ.nv = FQ.nv + dFQ.nv
    E.nv = E.nv + dE.nv
    Isym.nv = Isym.nv + dIsym.nv
    Iasym.nv = Iasym.nv + dIasym.nv
    Qsym.nv = Qsym.nv + dQsym.nv
    Qasym.nv = Qasym.nv + dQasym.nv
    H.nv = H.nv + dH.nv
    R.nv = R.nv + dR.nv
    D.nv = D.nv + dD.nv
  }
  
  Pop.nv = S.nv + FQ.nv + E.nv + Isym.nv + Iasym.nv + Qsym.nv + Qasym.nv + H.nv + R.nv + D.nv
  df.nv[i+1,] = list(i, Pop.nv, S.nv, FQ.nv, E.nv, Isym.nv, Iasym.nv, Qsym.nv, Qasym.nv, H.nv, R.nv, D.nv)
                     # for debugging only
                     # , new.exposed.nv, quarantine.released.today.nv, new.quarantined.nv, new.infected.all.nv, new.infected.sym.nv, confirmed.sym.nv, nonconfirmed.sym.nv, new.infected.asym.nv, confirmed.asym.nv, nonconfirmed.asym.nv, nonconfirmed.sym.to.H.nv, nonconfirmed.sym.to.R.nv, nonconfirmed.sym.to.D.nv, nonconfirmed.asym.to.R.nv, nonconfirmed.asym.to.D.nv, Qsym.to.H.nv, Qsym.to.R.nv, Qsym.to.D.nv, Qasym.to.R.nv, Qasym.to.D.nv, H.to.R.nv, H.to.D.nv)
  
  ### Immediate calculations (for next day statistics)
  new.exposed.nv = (S.nv/N) * (I.rate.sym.nv * Isym.nv + I.rate.asym.nv * Iasym.nv)
  quarantine.released.today.nv = FQ.nv * 1/day.q
  new.quarantined.nv = S.nv * p.test.all.nv * p.fp.all.nv
  new.infected.all.nv = E.rate * E.nv #total infected
    # infected symptomatic
  new.infected.sym.nv = new.infected.all.nv * p.sym.nv
  confirmed.sym.nv = Isym.nv * p.test.sym.nv * p.tp.sym.nv #tested & true positive
  nonconfirmed.sym.nv = Isym.nv - confirmed.sym.nv #not-tested & false negative
    # infected asymptomatic
  new.infected.asym.nv = new.infected.all.nv - new.infected.sym.nv
  confirmed.asym.nv = Iasym.nv * p.test.asym.nv * p.tp.asym.nv
  nonconfirmed.asym.nv = Iasym.nv - confirmed.asym.nv
    # transition between compartments (I, Q, H, R, D)
  nonconfirmed.sym.to.H.nv = nonconfirmed.sym.nv * H.rate.nv
  nonconfirmed.sym.to.R.nv = nonconfirmed.sym.nv * R.rate.sym.nv
  nonconfirmed.sym.to.D.nv = nonconfirmed.sym.nv * D.rate.sym.nv
  nonconfirmed.asym.to.R.nv = nonconfirmed.asym.nv * R.rate.asym.nv
  Qsym.to.H.nv = Qsym.nv * H.rate.nv
  Qsym.to.R.nv = Qsym.nv * R.rate.sym.nv
  Qsym.to.D.nv = Qsym.nv * D.rate.sym.nv
  Qasym.to.R.nv = Qasym.nv * R.rate.asym.nv
  H.to.R.nv = H.nv * R.rate.h.nv
  H.to.D.nv = H.nv * D.rate.h.nv

  ### Calculate changes in each compartment
  dS.nv = - new.exposed.nv - new.quarantined.nv + quarantine.released.today.nv
  dFQ.nv = new.quarantined.nv - quarantine.released.today.nv
  dE.nv = new.exposed.nv - new.infected.all.nv
  dIsym.nv = new.infected.sym.nv - confirmed.sym.nv - nonconfirmed.sym.to.H.nv - nonconfirmed.sym.to.R.nv - nonconfirmed.sym.to.D.nv
  dIasym.nv = new.infected.asym.nv - confirmed.asym.nv - nonconfirmed.asym.to.R.nv
  dQsym.nv = confirmed.sym.nv - Qsym.to.H.nv - Qsym.to.R.nv - Qsym.to.D.nv
  dQasym.nv = confirmed.asym.nv - Qasym.to.R.nv
  dH.nv = nonconfirmed.sym.to.H.nv + Qsym.to.H.nv - H.to.D.nv  - H.to.R.nv
  dR.nv = H.to.R.nv + nonconfirmed.sym.to.R.nv + Qsym.to.R.nv + Qasym.to.R.nv +  nonconfirmed.asym.to.R.nv
  dD.nv = H.to.D.nv + nonconfirmed.sym.to.D.nv + Qsym.to.D.nv
}
```

The below code chunk is assuming 100% population is Vulnerable

```{r}
N = 1000
p.vulnerable = 1
N.v = N * p.vulnerable

# Parameters Declaration for V sub-population

### Mutable Parameters (Testing effectiveness, quarantine days)
p.test.sym.v = 0.7 #percentage of testing for symptomatic group
p.test.asym.v = 0.3 #percentage of testing for asymptomatic group
p.test.all.v = p.test.asym.v/4 #percentage of testing for all V sub-population
p.fp.all.v = .01 #false positive percentage of testing for all V sub-population
p.tp.sym.v = .98 #true positive percentage for symptomatic group
p.tp.asym.v = .95 #true positive percentage for asymptomatic group
day.q = 14 #quarantine period (days)

### Immutatble Parameters (disease's rates)
p.ns.v = 0 #percentage of initial non-susceptible
p.sym.v = .5 #percentage of infected being symptomatic
day.i = 10 #incubation period (days)
E.rate = 1 / day.i #exposure rate

I.rate.sym.v = 1.5 #infection rate for symptomatic group
I.rate.asym.v = 1.5 #infection rate for asymptomatic group

H.rate.v = .1 #hospitalization rate

R.rate.sym.v = .3 #recovery rate for symptomatic group
R.rate.asym.v = .4 #recovery rate for asymptomatic group
R.rate.h.v = .5 #recovery rate for hospitalized group

D.rate.sym.v = .2 #death rate for symptomatic group
D.rate.asym.v = .1 #death rate for asymptomatic group
D.rate.h.v = .2 #death rate for hospitalized group
  
df.v = data.frame(Day = numeric(),
                Pop.v = numeric(),
                S.v = numeric(),
                FQ.v = numeric (),
                E.v = numeric(),
                Isym.v = numeric(),
                Iasym.v = numeric(),
                Qsym.v = numeric(),
                Qasym.v = numeric(),
                H.v = numeric(),
                R.v = numeric(),
                D.v = numeric()
                # for debugging only
                # new.exposed.v = numeric(),
                # quarantine.released.today.v = numeric(),
                # new.quarantined.v = numeric(),
                # new.infected.all.v = numeric(),
                # new.infected.sym.v = numeric(),
                # confirmed.sym.v = numeric(),
                # nonconfirmed.sym.v = numeric(),
                # new.infected.asym.v = numeric(),
                # confirmed.asym.v = numeric(),
                # nonconfirmed.asym.v = numeric(),
                # nonconfirmed.sym.to.H.v = numeric(),
                # nonconfirmed.sym.to.R.v = numeric(),
                # nonconfirmed.sym.to.D.v = numeric(),
                # nonconfirmed.asym.to.R.v = numeric(),
                # nonconfirmed.asym.to.D.v = numeric(),
                # Qsym.to.H.v = numeric(),
                # Qsym.to.R.v = numeric(),
                # Qsym.to.D.v = numeric(),
                # Qasym.to.R.v = numeric(),
                # Qasym.to.D.v = numeric(),
                # H.to.R.v = numeric(),
                # H.to.D.v = numeric()
                )
for (i in 0:100) {
  
  if(i == 0){
    ### Initial setting (day 0)
    Isym.v = 5 #initial infected symptomatic
    Iasym.v = 0 #initial infected asymptomatic
    R.v = N.v * p.ns.v #initial "recovered" i.e non-susceptible
    S.v = N.v - Isym.v - Iasym.v - R.v
    FQ.v = 0
    E.v = 0
    D.v = 0
    H.v = 0
    Qsym.v = 0
    Qasym.v = 0
  } else {
    ### Current day calculations
    S.v = S.v + dS.v
    FQ.v = FQ.v + dFQ.v
    E.v = E.v + dE.v
    Isym.v = Isym.v + dIsym.v
    Iasym.v = Iasym.v + dIasym.v
    Qsym.v = Qsym.v + dQsym.v
    Qasym.v = Qasym.v + dQasym.v
    H.v = H.v + dH.v
    R.v = R.v + dR.v
    D.v = D.v + dD.v
  }
  
  Pop.v = S.v + FQ.v + E.v + Isym.v + Iasym.v + Qsym.v + Qasym.v + H.v + R.v + D.v
  df.v[i+1,] = list(i, Pop.v, S.v, FQ.v, E.v, Isym.v, Iasym.v, Qsym.v, Qasym.v, H.v, R.v, D.v)
                # for debugging only
                # , new.exposed.v, quarantine.released.today.v, new.quarantined.v, new.infected.all.v, new.infected.sym.v, confirmed.sym.v, nonconfirmed.sym.v, new.infected.asym.v, confirmed.asym.v, nonconfirmed.asym.v, nonconfirmed.sym.to.H.v, nonconfirmed.sym.to.R.v, nonconfirmed.sym.to.D.v, nonconfirmed.asym.to.R.v, nonconfirmed.asym.to.D.v, Qsym.to.H.v, Qsym.to.R.v, Qsym.to.D.v, Qasym.to.R.v, Qasym.to.D.v, H.to.R.v, H.to.D.v)
  
  ### Immediate calculations (for next day statistics)
  new.exposed.v = (S.v/N) * (I.rate.sym.v * Isym.v + I.rate.asym.v * Iasym.v)
  quarantine.released.today.v = FQ.v * 1/day.q
  new.quarantined.v = S.v * p.test.all.v * p.fp.all.v
  new.infected.all.v = E.rate * E.v #total infected
    # infected symptomatic
  new.infected.sym.v = new.infected.all.v * p.sym.v
  confirmed.sym.v = Isym.v * p.test.sym.v * p.tp.sym.v #tested & true positive
  nonconfirmed.sym.v = Isym.v - confirmed.sym.v #not-tested & false negative
    # infected asymptomatic
  new.infected.asym.v = new.infected.all.v - new.infected.sym.v
  confirmed.asym.v = Iasym.v * p.test.asym.v * p.tp.asym.v
  nonconfirmed.asym.v = Iasym.v - confirmed.asym.v
    # transition between compartments (I, Q, H, R, D)
  nonconfirmed.sym.to.H.v = nonconfirmed.sym.v * H.rate.v
  nonconfirmed.sym.to.R.v = nonconfirmed.sym.v * R.rate.sym.v
  nonconfirmed.sym.to.D.v = nonconfirmed.sym.v * D.rate.sym.v
  nonconfirmed.asym.to.R.v = nonconfirmed.asym.v * R.rate.asym.v
  nonconfirmed.asym.to.D.v = nonconfirmed.asym.v * D.rate.asym.v
  Qsym.to.H.v = Qsym.v * H.rate.v
  Qsym.to.R.v = Qsym.v * R.rate.sym.v
  Qsym.to.D.v = Qsym.v * D.rate.sym.v
  Qasym.to.R.v = Qasym.v * R.rate.asym.v
  Qasym.to.D.v = Qasym.v * D.rate.asym.v
  H.to.R.v = H.v * R.rate.h.v
  H.to.D.v = H.v * D.rate.h.v

  ### Calculate changes in each compartment
  dS.v = - new.exposed.v - new.quarantined.v + quarantine.released.today.v
  dFQ.v = new.quarantined.v - quarantine.released.today.v
  dE.v = new.exposed.v - new.infected.all.v
  dIsym.v = new.infected.sym.v - confirmed.sym.v - nonconfirmed.sym.to.H.v - nonconfirmed.sym.to.R.v - nonconfirmed.sym.to.D.v
  dIasym.v = new.infected.asym.v - confirmed.asym.v - nonconfirmed.asym.to.R.v - nonconfirmed.asym.to.D.v
  dQsym.v = confirmed.sym.v - Qsym.to.H.v - Qsym.to.R.v - Qsym.to.D.v
  dQasym.v = confirmed.asym.v - Qasym.to.R.v - Qasym.to.D.v
  dH.v = nonconfirmed.sym.to.H.v + Qsym.to.H.v - H.to.D.v - H.to.R.v
  dR.v = H.to.R.v + nonconfirmed.sym.to.R.v + nonconfirmed.asym.to.R.v + Qsym.to.R.v + Qasym.to.R.v
  dD.v = H.to.D.v + nonconfirmed.sym.to.D.v + nonconfirmed.asym.to.D.v + Qsym.to.D.v + Qasym.to.D.v
}
```

The below code chunk is using both vulnerable and non-vulnerable in the population:

```{r}
# Population is split into 2 sub-populations:
# Vulnerable (V) and Non-Vulnerable (NV)
N = 1000
p.vulnerable = .5
N.v = N * p.vulnerable
N.nv = N - N.v

# Shared parameters
day.q = 14 #quarantine period (days)
day.i = 10 #incubation period (days)
E.rate = 1 / day.i #exposure rate
I.rate.sym = 1.5 #infection rate for symptomatic group
I.rate.asym = 1.5 #infection rate for asymptomatic group

# Parameters Declaration for NV sub-population

### Mutable Parameters (Testing effectiveness, quarantine days)
p.test.sym.nv = 0 #percentage of testing for symptomatic group
p.test.asym.nv = 0 #percentage of testing for asymptomatic group
p.test.all.nv = p.test.asym.nv/2 #percentage of testing for all NV sub-population
p.fp.all.nv = .01 #false positive percentage of testing for all NV sub-population
p.tp.sym.nv = .98 #true positive percentage for symptomatic group
p.tp.asym.nv = .95 #true positive percentage for asymptomatic group

### Immutatble Parameters (disease's rates)
p.ns.nv = .25 #percentage of initial non-susceptible
p.sym.nv = .5 #percentage of infected being symptomatic

H.rate.nv = .1 #hospitalization rate

R.rate.sym.nv = .09 #recovery rate for symptomatic group
R.rate.asym.nv = .1 #recovery rate for asymptomatic group
R.rate.h.nv = .05333 #recovery rate for hospitalized group

D.rate.sym.nv = .01 #death rate for symptomatic group
D.rate.asym.nv = .05 #death rate for asymptomatic group
D.rate.h.nv = 0.01333 #death rate for hospitalized group

# Parameters Declaration for V sub-population

### Mutable Parameters (Testing effectiveness, quarantine days)
p.test.sym.v = 0.7 #percentage of testing for symptomatic group
p.test.asym.v = 0.3 #percentage of testing for asymptomatic group
p.test.all.v = p.test.asym.v/4 #percentage of testing for all V sub-population
p.fp.all.v = .01 #false positive percentage of testing for all V sub-population
p.tp.sym.v = .98 #true positive percentage for symptomatic group
p.tp.asym.v = .95 #true positive percentage for asymptomatic group

### Immutatble Parameters (disease's rates)
p.ns.v = 0 #percentage of initial non-susceptible
p.sym.v = .5 #percentage of infected being symptomatic

H.rate.v = .1 #hospitalization rate

R.rate.sym.v = .3 #recovery rate for symptomatic group
R.rate.asym.v = .4 #recovery rate for asymptomatic group
R.rate.h.v = .5 #recovery rate for hospitalized group

D.rate.sym.v = .2 #death rate for symptomatic group
D.rate.asym.v = .1 #death rate for asymptomatic group
D.rate.h.v = .2 #death rate for hospitalized group

df = data.frame(Day = numeric(),
                # NV group
                Pop.nv = numeric(),
                S.nv = numeric(),
                FQ.nv = numeric (),
                E.nv = numeric(),
                Isym.nv = numeric(),
                Iasym.nv = numeric(),
                Qsym.nv = numeric(),
                Qasym.nv = numeric(),
                H.nv = numeric(),
                R.nv = numeric(),
                D.nv = numeric(),
                # V group
                Pop.v = numeric(),
                S.v = numeric(),
                FQ.v = numeric (),
                E.v = numeric(),
                Isym.v = numeric(),
                Iasym.v = numeric(),
                Qsym.v = numeric(),
                Qasym.v = numeric(),
                H.v = numeric(),
                R.v = numeric(),
                D.v = numeric())

for (i in 0:100) {
  
  if(i == 0){
    ### Initial setting (day 0)
    Isym.nv = 5 #initial infected symptomatic
    Iasym.nv = 0 #initial infected asymptomatic
    R.nv = N.nv * p.ns.nv #initial "recovered" i.e non-susceptible
    S.nv = N.nv - Isym.nv - Iasym.nv - R.nv
    FQ.nv = 0
    E.nv = 0
    D.nv = 0
    H.nv = 0
    Qsym.nv = 0
    Qasym.nv = 0
    
    Isym.v = 5 #initial infected symptomatic
    Iasym.v = 0 #initial infected asymptomatic
    R.v = N.v * p.ns.v #initial "recovered" i.e non-susceptible
    S.v = N.v - Isym.v - Iasym.v - R.v
    FQ.v = 0
    E.v = 0
    D.v = 0
    H.v = 0
    Qsym.v = 0
    Qasym.v = 0
  } else {
    ### Current day calculations
    S.nv = S.nv + dS.nv
    FQ.nv = FQ.nv + dFQ.nv
    E.nv = E.nv + dE.nv
    Isym.nv = Isym.nv + dIsym.nv
    Iasym.nv = Iasym.nv + dIasym.nv
    Qsym.nv = Qsym.nv + dQsym.nv
    Qasym.nv = Qasym.nv + dQasym.nv
    H.nv = H.nv + dH.nv
    R.nv = R.nv + dR.nv
    D.nv = D.nv + dD.nv
    
    S.v = S.v + dS.v
    FQ.v = FQ.v + dFQ.v
    E.v = E.v + dE.v
    Isym.v = Isym.v + dIsym.v
    Iasym.v = Iasym.v + dIasym.v
    Qsym.v = Qsym.v + dQsym.v
    Qasym.v = Qasym.v + dQasym.v
    H.v = H.v + dH.v
    R.v = R.v + dR.v
    D.v = D.v + dD.v
  }
  
  Pop.nv = S.nv + FQ.nv + E.nv + Isym.nv + Iasym.nv + Qsym.nv + Qasym.nv + H.nv + R.nv + D.nv
  Pop.v = S.v + FQ.v + E.v + Isym.v + Iasym.v + Qsym.v + Qasym.v + H.v + R.v + D.v
  df[i,] = list(i, Pop.nv, S.nv, FQ.nv, E.nv, Isym.nv, Iasym.nv, Qsym.nv, Qasym.nv, H.nv, R.nv, D.nv,
                   Pop.v, S.v, FQ.v, E.v, Isym.v, Iasym.v, Qsym.v, Qasym.v, H.v, R.v, D.v)
  
  ### Immediate calculations (for next day statistics)
  new.exposed.nv = (S.nv/N) * (I.rate.sym * Isym.nv + I.rate.asym * Iasym.nv + I.rate.sym * Isym.v + I.rate.asym * Iasym.v)
  quarantine.released.today.nv = FQ.nv * 1/day.q
  new.quarantined.nv = S.nv * p.test.all.nv * p.fp.all.nv
  new.infected.all.nv = E.rate * E.nv #total infected
  # infected symptomatic
  new.infected.sym.nv = new.infected.all.nv * p.sym.nv
  confirmed.sym.nv = Isym.nv * p.test.sym.nv * p.tp.sym.nv #tested & true positive
  nonconfirmed.sym.nv = Isym.nv - confirmed.sym.nv #not-tested & false negative
  # infected asymptomatic
  new.infected.asym.nv = new.infected.all.nv - new.infected.sym.nv
  confirmed.asym.nv = Iasym.nv * p.test.asym.nv * p.tp.asym.nv
  nonconfirmed.asym.nv = Iasym.nv - confirmed.asym.nv
  # transition between compartments (I, Q, H, R, D)
  nonconfirmed.sym.to.H.nv = nonconfirmed.sym.nv * H.rate.nv
  nonconfirmed.sym.to.R.nv = nonconfirmed.sym.nv * R.rate.sym.nv
  nonconfirmed.sym.to.D.nv = nonconfirmed.sym.nv * D.rate.sym.nv
  nonconfirmed.asym.to.R.nv = nonconfirmed.asym.nv * R.rate.asym.nv
  Qsym.to.H.nv = Qsym.nv * H.rate.nv
  Qsym.to.R.nv = Qsym.nv * R.rate.sym.nv
  Qsym.to.D.nv = Qsym.nv * D.rate.sym.nv
  Qasym.to.R.nv = Qasym.nv * R.rate.asym.nv
  H.to.R.nv = H.nv * R.rate.h.nv
  H.to.D.nv = H.nv * D.rate.h.nv
  
  ### Calculate changes in each compartment
  dS.nv = - new.exposed.nv - new.quarantined.nv + quarantine.released.today.nv
  dFQ.nv = new.quarantined.nv - quarantine.released.today.nv
  dE.nv = new.exposed.nv - new.infected.all.nv
  dIsym.nv = new.infected.sym.nv - confirmed.sym.nv - nonconfirmed.sym.to.H.nv - nonconfirmed.sym.to.R.nv - nonconfirmed.sym.to.D.nv
  dIasym.nv = new.infected.asym.nv - confirmed.asym.nv - nonconfirmed.asym.to.R.nv
  dQsym.nv = confirmed.sym.nv - Qsym.to.H.nv - Qsym.to.R.nv - Qsym.to.D.nv
  dQasym.nv = confirmed.asym.nv - Qasym.to.R.nv
  dH.nv = nonconfirmed.sym.to.H.nv + Qsym.to.H.nv - H.to.D.nv  - H.to.R.nv
  dR.nv = H.to.R.nv + nonconfirmed.sym.to.R.nv + Qsym.to.R.nv + Qasym.to.R.nv +  nonconfirmed.asym.to.R.nv
  dD.nv = H.to.D.nv + nonconfirmed.sym.to.D.nv + Qsym.to.D.nv
  
  ### Immediate calculations (for next day statistics)
  new.exposed.v = (S.v/N) * (I.rate.sym * Isym.nv + I.rate.asym * Iasym.nv + I.rate.sym * Isym.v + I.rate.asym * Iasym.v)
  quarantine.released.today.v = FQ.v * 1/day.q
  new.quarantined.v = S.v * p.test.all.v * p.fp.all.v
  new.infected.all.v = E.rate * E.v #total infected
  # infected symptomatic
  new.infected.sym.v = new.infected.all.v * p.sym.v
  confirmed.sym.v = Isym.v * p.test.sym.v * p.tp.sym.v #tested & true positive
  nonconfirmed.sym.v = Isym.v - confirmed.sym.v #not-tested & false negative
  # infected asymptomatic
  new.infected.asym.v = new.infected.all.v - new.infected.sym.v
  confirmed.asym.v = Iasym.v * p.test.asym.v * p.tp.asym.v
  nonconfirmed.asym.v = Iasym.v - confirmed.asym.v
  # transition between compartments (I, Q, H, R, D)
  nonconfirmed.sym.to.H.v = nonconfirmed.sym.v * H.rate.v
  nonconfirmed.sym.to.R.v = nonconfirmed.sym.v * R.rate.sym.v
  nonconfirmed.sym.to.D.v = nonconfirmed.sym.v * D.rate.sym.v
  nonconfirmed.asym.to.R.v = nonconfirmed.asym.v * R.rate.asym.v
  nonconfirmed.asym.to.D.v = nonconfirmed.asym.v * D.rate.asym.v
  Qsym.to.H.v = Qsym.v * H.rate.v
  Qsym.to.R.v = Qsym.v * R.rate.sym.v
  Qsym.to.D.v = Qsym.v * D.rate.sym.v
  Qasym.to.R.v = Qasym.v * R.rate.asym.v
  Qasym.to.D.v = Qasym.v * D.rate.asym.v
  H.to.R.v = H.v * R.rate.h.v
  H.to.D.v = H.v * D.rate.h.v
  
  ### Calculate changes in each compartment
  dS.v = - new.exposed.v - new.quarantined.v + quarantine.released.today.v
  dFQ.v = new.quarantined.v - quarantine.released.today.v
  dE.v = new.exposed.v - new.infected.all.v
  dIsym.v = new.infected.sym.v - confirmed.sym.v - nonconfirmed.sym.to.H.v - nonconfirmed.sym.to.R.v - nonconfirmed.sym.to.D.v
  dIasym.v = new.infected.asym.v - confirmed.asym.v - nonconfirmed.asym.to.R.v - nonconfirmed.asym.to.D.v
  dQsym.v = confirmed.sym.v - Qsym.to.H.v - Qsym.to.R.v - Qsym.to.D.v
  dQasym.v = confirmed.asym.v - Qasym.to.R.v - Qasym.to.D.v
  dH.v = nonconfirmed.sym.to.H.v + Qsym.to.H.v - H.to.D.v - H.to.R.v
  dR.v = H.to.R.v + nonconfirmed.sym.to.R.v + nonconfirmed.asym.to.R.v + Qsym.to.R.v + Qasym.to.R.v
  dD.v = H.to.D.v + nonconfirmed.sym.to.D.v + nonconfirmed.asym.to.D.v + Qsym.to.D.v + Qasym.to.D.v
}
```

